In [7]:
import pandas as pd 
import numpy as np

In [10]:
file = "player_data.csv"
nba_hurt = pd.read_csv(file)
nba_hurt

,name,year_start,year_end,position,height,weight,birth_date,college
0,Alaa Abdelnaby,1991,1995,F-C,6-10,240.0,"June 24, 1968",Duke University
1,Zaid Abdul-Aziz,1969,1978,C-F,6-9,235.0,"April 7, 1946",Iowa State University
2,Kareem Abdul-Jabbar,1970,1989,C,7-2,225.0,"April 16, 1947","University of California, Los Angeles"
3,Mahmoud Abdul-Rauf,1991,2001,G,6-1,162.0,"March 9, 1969",Louisiana State University
4,Tariq Abdul-Wahad,1998,2003,F,6-6,223.0,"November 3, 1974",San Jose State University
5,Shareef Abdur-Rahim,1997,2008,F,6-9,225.0,"December 11, 1976",University of California
6,Tom Abernethy,1977,1981,F,6-7,220.0,"May 6, 1954",Indiana University
7,Forest Able,1957,1957,G,6-3,180.0,"July 27, 1932",Western Kentucky University
8,John Abramovic,1947,1948,F,6-3,195.0,"February 9, 1919",Salem International University
9,Alex Abrines,2017,2018,G-F,6-6,190.0,"August 1, 1993",NaN
10,Alex Acker,2006,2009,G,6-5,185.0,"January 21, 1983",Pepperdine University
11,Don Ackerman,1954,1954,G,6-0,183.0,"September 4, 1930",Long Island University
12,Mark Acres,1988,1993,F-C,6-11,220.0,"November 15, 1962",Oral Roberts University
13,Bud Acton,1968,1968,F,6-6,210.0,"January 11, 1942",Hillsdale College
14,Quincy Acy,2013,2018,F,6-7,240.0,"October 6, 1990",Baylor University
15,Alvan Adams,1976,1988,C-F,6-9,210.0,"July 19, 1954",University of Oklahoma
16,Don Adams,1971,1977,F,6-6,210.0,"November 27, 1947",Northwestern University
17,George Adams,1973,1975,F-G,6-5,210.0,"May 15, 1949",Gardner-Webb University
18,Hassan Adams,2007,2009,G,6-4,220.0,"June 20, 1984",University of Arizona
19,Jordan Adams,2015,2016,G,6-5,209.0,"July 8, 1994","University of California, Los Angeles"
20,Michael Adams,1986,1996,G,5-10,162.0,"January 19, 1963",Boston College
21,Steven Adams,2014,2018,C,7-0,255.0,"July 20, 1993",University of Pittsburgh
22,Rafael Addison,1987,1997,F-G,6-7,215.0,"July 22, 1964",Syracuse University
23,Bam Adebayo,2018,2018,C-F,6-10,243.0,"July 18, 1997",University of Kentucky
24,Rick Adelman,1969,1975,G,6-1,175.0,"June 16, 1946",Loyola Marymount University
25,Jeff Adrien,2011,2015,F,6-7,245.0,"February 10, 1986",University of Connecticut
26,Arron Afflalo,2008,2018,G,6-5,210.0,"October 15, 1985","University of California, Los Angeles"
27,Maurice Ager,2007,2011,G,6-5,202.0,"February 9, 1984",Michigan State University
28,Mark Aguirre,1982,1994,F-G,6-6,232.0,"December 10, 1959",DePaul University
29,Blake Ahearn,2008,2012,G,6-2,190.0,"May 27, 1984",Missouri State University
...,...,...,...,...,...,...,...,...
4520,James Young,2015,2017,G-F,6-6,215.0,"August 16, 1995",University of Kentucky
4521,Joe Young,2016,2018,G,6-2,180.0,"June 27, 1992",University of Oregon
4522,Korleone Young,1999,1999,F,6-7,213.0,"December 31, 1978",NaN
4523,Michael Young,1985,1990,F-G,6-7,220.0,"January 2, 1961",University of Houston
4524,Nick Young,2008,2018,G-F,6-7,210.0,"June 1, 1985",University of Southern California
4525,Perry Young,1987,1987,G,6-5,210.0,"August 4, 1963",Virginia Polytechnic Institute and State Unive...
4526,Sam Young,2010,2013,F,6-6,220.0,"June 1, 1985",University of Pittsburgh
4527,Thaddeus Young,2008,2018,F,6-8,221.0,"June 21, 1988",Georgia Institute of Technology
4528,Tim Young,2000,2000,C,7-0,220.0,"February 6, 1976",Stanford University
4529,Sun Yue,2009,2009,G,6-9,205.0,"November 6, 1985",NaN
4530,Max Zaslofsky,1947,1956,G-F,6-2,170.0,"December 7, 1925",St. John's University
4531,Zeke Zawoluk,1953,1955,F-C,6-7,215.0,"October 13, 1930",St. John's University
4532,Cody Zeller,2014,2018,C-F,7-0,240.0,"October 5, 1992",Indiana University
4533,Dave Zeller,1962,1962,G,6-1,175.0,"June 8, 1939",Miami University
4534,Gary Zeller,1971,1972,G,6-3,205.0,"November 20, 1947",Drake University
4535,Harry Zeller,1947,1947,C-F,6-4,210.0,"July 10, 1919",Washington & Jefferson College
4536,Luke Zeller,2013,2013,C,6-11,245.0,"April 7, 1987",University of Notre Dame
4537,Tyler Zeller,2013,2018,F-C,7-0,253.0,"January 17, 1990",University of North Carolina
4538,Tony Zeno,1980,1980,F,6-8,210.0,"October 1, 1957",Arizona State University
4539,Phil Zevenbergen,1988,1988,C,6-10,230.0,"April 13, 1964",University of Washington
4540,Wang Zhizhi,2001,2005,C,7-0,255.0,"July 8, 1977",NaN
4541,George Zidek,1996,1998,C,7-0,250.0,"August 2, 1973","University of California, Los Angeles"
4542,Derrick Zimmerman,2006,2006,G,6-3,195.0,"December 2, 1981",Mississippi State University
4543,Stephen Zimmerman,2017,2017,C,7-0,240.0,"September 9, 1996","University of Nevada, Las Vegas"
4544,Paul Zipser,2017,2018,G-F,6-8,215.0,"February 18, 1994",NaN
4545,Ante Zizic,2018,2018,F-C,6-11,250.0,"January 4, 1997",NaN
4546,Jim Zoet,1983,1983,C,7-1,240.0,"December 20, 1953",Kent State University
4547,Bill Zopf,1971,1971,G,6-1,170.0,"June 7, 1948",Duquesne University
4548,Ivica Zubac,2017,2018,C,7-1,265.0,"March 18, 1997",NaN
4549,Matt Zunic,1949,1949,G-F,6-3,195.0,"December 19, 1919",George Washington University

In [9]:
inj_team = nba_hurt.groupby(["Team"])
inj_team_count = inj_team["name"].count()
inj_team_df = pd.DataFrame({"Number of Injuries": inj_team_count})
team_df = inj_team_df.sort_values("Number of Injuries", ascending = False)

KeyError: 'Team'